#!/usr/bin/env bash
# compile.sh - Build MongoDB 8.3.8 (mongod, mongos, mongo shell) with a local
# host gcc toolchain, online or fully offline.
#
# The MongoDB build normally downloads a prebuilt "mongodbtoolchain" compiler
# tarball and talks to MongoDB's remote build services. This script instead:
#   * uses a local gcc (>= 14) via Bazel's native C++ toolchain autodetection,
#   * disables every remote/network service (EngFlow remote exec/cache, BES),
#   * reads all external dependencies from a Bazel repository cache, which the
#     accompanying package pre-populates so no network is ever needed,
#   * restores the compiler flags/defines that MongoDB's own toolchain config
#     would have injected (they are lost when not using the mongo toolchain).
#
# Usage:
#   ./compile.sh [extra bazel args...]
#
# Environment overrides (all optional):
#   SOURCE_DIR    REQUIRED: your mongo r8.3.8 checkout with the offline patch applied
#   GCC_PREFIX    gcc install prefix           (default: /usr)
#   CC, CXX, AR   explicit compiler paths      (default: $GCC_PREFIX/bin/{gcc,g++,gcc-ar})
#   BAZEL_REAL    mongo-forked bazel binary    (default: <script dir>/tools/bazel-7.5.0-...)
#   REPO_CACHE    bazel repository cache dir   (default: <script dir>/cache/repo_cache)
#   TARGET        bazel target to build        (default: install-devcore)
#   MONGO_VERSION version to stamp             (default: 8.3.8)
#   OFFLINE       1 = enforce fully-offline behavior (lockfile_mode=error) (default: 0)
#   MARCH         -march value                 (default: sandybridge, mongo's own default)
#   STATIC_CXX_RUNTIME 1 = link libstdc++/libgcc statically (default: 1)
#   JOBS          bazel --jobs                 (default: bazel decides)
#   OUTPUT_USER_ROOT  bazel output user root   (default: <script dir>/bazel-root)
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# The mongo checkout to build: your existing source tree at r8.3.8 with
# patches/mongo-8.3.8-offline.patch applied (git apply patches/...).
SOURCE_DIR=${SOURCE_DIR:-}
[ -n "$SOURCE_DIR" ] || { echo "ERROR: set SOURCE_DIR to your mongo r8.3.8 checkout (with the offline patch applied)" >&2; exit 1; }
OUTPUT_USER_ROOT=${OUTPUT_USER_ROOT:-$SCRIPT_DIR/bazel-root}
GCC_PREFIX=${GCC_PREFIX:-/usr}
BAZEL_REAL=${BAZEL_REAL:-$SCRIPT_DIR/tools/bazel-7.5.0-mongo_06d753863d-linux-x86_64}
REPO_CACHE=${REPO_CACHE:-$SCRIPT_DIR/cache/repo_cache}
TARGET=${TARGET:-install-devcore}
MONGO_VERSION=${MONGO_VERSION:-8.3.8}
OFFLINE=${OFFLINE:-0}
MARCH=${MARCH:-sandybridge}
STATIC_CXX_RUNTIME=${STATIC_CXX_RUNTIME:-1}

CC=${CC:-$GCC_PREFIX/bin/gcc}
CXX=${CXX:-$GCC_PREFIX/bin/g++}
AR=${AR:-$GCC_PREFIX/bin/gcc-ar}

die() { echo "ERROR: $*" >&2; exit 1; }

# ---- sanity checks ---------------------------------------------------------
[ -d "$SOURCE_DIR" ] || die "SOURCE_DIR not found: $SOURCE_DIR"
[ -f "$SOURCE_DIR/tools/bazel" ] || die "$SOURCE_DIR does not look like a mongo source tree (tools/bazel missing)"
[ -x "$BAZEL_REAL" ] || die "bazel binary not found/executable: $BAZEL_REAL"
[ -x "$CC" ] || die "C compiler not found: $CC (set GCC_PREFIX or CC)"
[ -x "$CXX" ] || die "C++ compiler not found: $CXX"
[ -x "$AR" ] || { AR=$GCC_PREFIX/bin/ar; [ -x "$AR" ] || AR=/usr/bin/ar; }
[ -x "$AR" ] || die "ar not found; install binutils or set AR"

GCC_MAJOR=$("$CC" -dumpversion | cut -d. -f1)
[ "$GCC_MAJOR" -ge 14 ] 2>/dev/null || die "gcc >= 14 required, found $("$CC" --version | head -1)"

[ -f /usr/include/openssl/ssl.h ] \
    || die "missing system header openssl/ssl.h (install openssl-devel)"
[ -f /usr/include/curl/curl.h ] || [ -f "/usr/include/$(uname -m)-linux-gnu/curl/curl.h" ] \
    || die "missing system header curl/curl.h (install libcurl-devel)"

mkdir -p "$REPO_CACHE"
REPO_CACHE=$(cd "$REPO_CACHE" && pwd)
BAZEL_REAL=$(cd "$(dirname "$BAZEL_REAL")" && pwd)/$(basename "$BAZEL_REAL")
# Local wheelhouse with the lock-pinned PyPI wheels: rules_poetry downloads
# wheels with pip at build time, which our patched rules redirect to this
# directory (pip --no-index --find-links) so no network is needed.
WHEELHOUSE=${WHEELHOUSE:-$SCRIPT_DIR/cache/wheelhouse}
[ -d "$WHEELHOUSE" ] && WHEELHOUSE=$(cd "$WHEELHOUSE" && pwd) || WHEELHOUSE=""

if [ "$OFFLINE" = "1" ]; then
    LOCKFILE_MODE=error
else
    LOCKFILE_MODE=update
fi

# ---- .bazelrc.local: inherited by every bazel invocation, including the ----
# ---- nested ones the tools/bazel wrapper spawns (python/poetry bootstrap) --
cat > "$SOURCE_DIR/.bazelrc.local" <<EOF
# Generated by compile.sh - offline/local-gcc build settings.
$( [ -n "${OUTPUT_USER_ROOT:-}" ] && echo "startup --output_user_root=$OUTPUT_USER_ROOT" )
$( [ -n "$WHEELHOUSE" ] && echo "common --repo_env=MONGO_PIP_WHEELHOUSE=$WHEELHOUSE" )
common --repository_cache=$REPO_CACHE
common --lockfile_mode=$LOCKFILE_MODE
common --repo_env=no_c++_toolchain=1
# Kill every remote endpoint (EngFlow remote exec/cache, BES telemetry).
common --remote_executor=
common --experimental_remote_downloader=
common --remote_cache=
common --bes_backend=
common --bes_results_url=
common --legacy_important_outputs=false
EOF

# ---- environment -----------------------------------------------------------
export BAZELISK_SKIP_WRAPPER=1          # we invoke tools/bazel directly, no bazelisk
# The auto-header generator downloads ripgrep/fd from S3 unless given paths.
[ -x "$SCRIPT_DIR/tools/rg" ] && export RG_PATH=$SCRIPT_DIR/tools/rg
[ -x "$SCRIPT_DIR/tools/fd" ] && export FD_PATH=$SCRIPT_DIR/tools/fd
export BAZEL_REAL                       # tells tools/bazel which real bazel to run
export USE_NATIVE_TOOLCHAIN=1           # host platform without mongo-toolchain constraint
export GIT_PYTHON_REFRESH=quiet         # GitPython must not abort when git is absent
export NO_FLAG_SYNC=1                   # disable networked flag-sync service
export MONGO_VERSION                    # version stamp without 'git describe'
export CC CXX AR

# ---- flags MongoDB's own toolchain config would have provided --------------
DEFINES=(
    NDEBUG
    _FORTIFY_SOURCE=2
    _XOPEN_SOURCE=700
    _GNU_SOURCE
    ABSL_FORCE_ALIGNED_ACCESS
    ABSL_ALLOCATOR_NOTHROW
    BOOST_ENABLE_ASSERT_DEBUG_HANDLER
    BOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF
    BOOST_LOG_NO_SHORTHAND_NAMES
    BOOST_LOG_WITHOUT_THREAD_ATTR
    BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS
    BOOST_SYSTEM_NO_DEPRECATED
    BOOST_THREAD_USES_DATETIME
    BOOST_THREAD_VERSION=5
    BOOST_LOG_USE_NATIVE_SYSLOG
    PCRE2_STATIC
    SAFEINT_USE_INTRINSICS=0
)

COPTS=(
    -fno-strict-aliasing
    -fno-omit-frame-pointer
    -fstack-protector-strong
    -ffp-contract=off
    -pthread
    "-march=$MARCH"
    -mtune=generic
    -mprefer-vector-width=128
    # gcc 14.3 is newer than the officially supported 14.2: silence new warnings.
    -w
    -Wno-error
)

CXXOPTS=(
    -std=c++20
    -fsized-deallocation
)

LINKOPTS=(
    -pthread
    -rdynamic
    -Wl,--build-id
    -Wl,-z,noexecstack
    -lm
    -lresolv
)
if [ "$STATIC_CXX_RUNTIME" = "1" ]; then
    LINKOPTS+=(-static-libstdc++ -static-libgcc)
fi

BAZEL_ARGS=(
    build
    --config=local
    --repo_env=no_c++_toolchain=1
    --repo_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=0
    # Link libstdc++ statically, using the archive shipped with the selected
    # gcc (the driver searches its own lib dirs first). local_config_cc's
    # default link_libs is an explicit -lstdc++, which always picks the shared
    # lib and makes -static-libstdc++ a no-op; -l:libstdc++.a forces the
    # static archive.
    "--repo_env=BAZEL_LINKLIBS=-l%:libstdc++.a:-lm"
    --repo_env=CC="$CC"
    --repo_env=CXX="$CXX"
    --repo_env=AR="$AR"
    --repo_env=USE_NATIVE_TOOLCHAIN=1
    --action_env=CC="$CC"
    --action_env=CXX="$CXX"
    --action_env=AR="$AR"
    --define=MONGO_VERSION="$MONGO_VERSION"
    # External-repo headers (abseil, zlib, ...) are angle-included by mongo
    # sources; this feature exposes them via -isystem instead of -iquote.
    --features=external_include_paths
    --host_features=external_include_paths
    # MongoDB's own toolchain does not support a dynamic linker, so the .so
    # variant of every internal library is pruned from the build graph. Bazel's
    # native toolchain supports it, which would double-compile ~6300 files as
    # PIC and link ~10k unused shared libraries; disable to match upstream.
    --features=-supports_dynamic_linker
    --host_features=-supports_dynamic_linker
    --compilation_mode=opt
    --//bazel/config:opt=on
    --//bazel/config:dbg=False
    --//bazel/config:separate_debug=False
    --verbose_failures
)

for d in "${DEFINES[@]}"; do
    BAZEL_ARGS+=("--copt=-D$d" "--host_copt=-D$d")
done
for o in "${COPTS[@]}"; do
    BAZEL_ARGS+=("--copt=$o" "--host_copt=$o")
done
for o in "${CXXOPTS[@]}"; do
    BAZEL_ARGS+=("--cxxopt=$o" "--host_cxxopt=$o")
done
for o in "${LINKOPTS[@]}"; do
    BAZEL_ARGS+=("--linkopt=$o" "--host_linkopt=$o")
done

# The wrapper hook appends its own --config=local, whose expansion overrides
# an explicit --jobs; --local_cpu_resources limits concurrency reliably.
[ -n "${JOBS:-}" ] && BAZEL_ARGS+=("--jobs=$JOBS" "--local_cpu_resources=$JOBS")

# output_user_root is set via a startup line in .bazelrc.local (above) so the
# wrapper's nested bazel invocations share the same output root.
STARTUP_ARGS=()

echo "== compiler : $($CXX --version | head -1)"
echo "== bazel    : $BAZEL_REAL"
echo "== cache    : $REPO_CACHE (lockfile_mode=$LOCKFILE_MODE, offline=$OFFLINE)"
echo "== target   : $TARGET"

cd "$SOURCE_DIR"
exec tools/bazel "${STARTUP_ARGS[@]}" "${BAZEL_ARGS[@]}" "$@" "$TARGET"
